# Generated by Django 6.1.1 on 2026-09-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Lead Developer, Full-Stack Engineer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='e.g. Django, React, PostgreSQL', max_length=200, null=True),
        ),
    ]
